<GroceryGoScreenManager>:
    LoginScreen:
        id:LoginScreen
    RegisterScreen:
    MainScreen:
        id: MainScreen
    AddEventScreen:
        id: AddEventScreen
    AddFriendScreen:
        id:AddFriendScreen
    SettingsScreen:
        id:SettingScreen
    ChangeAvatorScreen:
        id:ChangeAvatorScreen
    FriendListScreen:
        id: FriendListScreen
    FriendEventScreen:
        id: FriendEventScreen
